apiVersion: v1
kind: Service

metadata:
  name: grpc-load-server-headless
  labels:
    {{- include "grpc-load-server.labels" . | nindent 4 }}

spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "grpc-load-server.selectorLabels" . | nindent 4 }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
