{{ if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "grpc-load-client.fullname" . }}
  labels:
    {{- include "grpc-load-client.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      interval: {{ .Values.monitoring.interval | quote }}
      port: http
  selector:
    matchLabels:
      {{- include "grpc-load-client.selectorLabels" . | nindent 6 }}
{{- end }}
